//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by missio.rc
//
#define IDOK2                           2
#define IDC_UPDATE                      2
#define IDR_MAINFRAME                   128
#define IDD_MAIN                        200
#define IDD_ABOUT                       201
#define IDD_FORUM                       202
#define IDD_UPDATE                      203
#define IDD_PHOTOALBUM                  204
#define IDD_ALARMS                      205
#define IDD_BIRTHDAYS                   206
#define IDD_SEARCHUSER                  207
#define IDD_MESSAGE                     208
#define IDD_USERINFO                    209
#define IDD_SENDMESSAGE                 210
#define IDD_NEWS                        211
#define IDD_CONNECTION                  212
#define IDD_LOGIN                       213
#define IDR_MAINMENU                    250
#define IDR_USERLISTMENU                251
#define IDR_SORTMENU                    252
#define IDR_FORUMPOSTMENU               253
#define IDR_USERMENU                    254
#define IDD_NOTIFICATION                293
#define IDD_LINKS                       294
#define IDR_PHOTOMENU                   295
#define IDD_OPTIONS                     296
#define IDC_USERLIST                    1000
#define IDC_INFORMERNAME                1005
#define IDS_EVENT_VERSION               1005
#define IDS_LOADING                     1006
#define IDS_APP_ERROR                   1007
#define IDS_APP_RUN_ERROR               1007
#define IDS_EVENT_FORUM                 1008
#define IDS_LOAD_FAILURE                1009
#define IDS_UPDATE_READY                1010
#define IDS_UNKNOWN                     1011
#define IDS_EVENT_PHOTOALBUM            1012
#define IDS_SHOW                        1013
#define IDS_UPDATING                    1014
#define IDC_INPUTTRAFFIC                1015
#define IDS_EVENT_NEWS                  1015
#define IDS_HIDE                        1016
#define IDS_UPDATE_FAILURE              1017
#define IDC_OUTPUTTRAFFIC               1018
#define IDS_APP_NAME                    1018
#define IDS_DOWNLOADING                 1019
#define IDC_FORUMTOPICLIST              1020
#define IDS_MESSAGE_WRONG_CRED          1020
#define IDS_NOT_REGISTERED              1021
#define IDC_MAINFRAME                   1022
#define IDS_MESSAGE_AUTH_REQUIRED       1022
#define IDS_FORUM                       1023
#define IDS_USER_PROFILE                1023
#define IDC_TRAFFICFRAME                1024
#define IDS_REG_PATH                    1024
#define IDS_BIRTHDAYS                   1025
#define IDC_ABOUT                       1026
#define IDS_APP_INIT_ERROR              1026
#define IDS_CONNECTED_USERS             1027
#define IDS_APP_TERM_ERROR              1027
#define IDS_CHAT_USERS                  1028
#define IDC_WINDOW                      1029
#define IDS_APP_PREV_ERROR              1029
#define IDS_CONNECTING                  1030
#define IDC_BIRTHDAYS                   1031
#define IDS_CONNECT_ERROR               1032
#define IDC_PHOTOALBUM                  1033
#define IDS_CONNECTED                   1034
#define IDC_NEWS                        1035
#define IDS_SHOW_FORUM                  1036
#define IDC_SEARCHUSER                  1037
#define IDS_SHOW_MENU                   1038
#define IDC_LINKS                       1039
#define IDS_SEX_HIDDEN                  1040
#define IDS_SEX_MALE                    1042
#define IDC_FORUM                       1043
#define IDS_SEX_FEMALE                  1044
#define IDC_ALARMS                      1045
#define IDS_ADD_ALARM                   1046
#define IDC_OPTIONS                     1047
#define IDS_REMOVE_ALARM                1048
#define IDS_SEND_CREDENTIALS            1049
#define IDC_EXIT                        1050
#define IDS_SEND_FAILURE                1051
#define IDC_STARTUPDATE                 1052
#define IDS_SEND_DENIED                 1053
#define IDC_PROGRESS                    1054
#define IDS_SEND_WAIT                   1055
#define IDC_MESSAGE                     1056
#define IDS_SEND_IGNORED                1057
#define IDC_FRAME                       1058
#define IDS_SEND_OFFLINE                1059
#define IDC_NICKNAME                    1060
#define IDS_SEND_SERVER                 1061
#define IDC_FULLNAME                    1062
#define IDS_AUTH_SERVER                 1063
#define IDC_SEX                         1065
#define IDS_AUTH_CLIENT                 1066
#define IDC_BIRTH_DAY                   1067
#define IDS_AUTH_BANNED                 1068
#define IDC_BIRTH_MONTH                 1068
#define IDC_BIRTH_YEAR                  1069
#define IDS_TRAFFIC_BYTES               1070
#define IDS_AUTH_FAILURE                1071
#define IDS_TRAFFIC_KBYTES              1072
#define IDC_HOMEPAGEBUTTON              1073
#define IDS_TRAFFIC_MBYTES              1074
#define IDC_HOMEPAGE                    1075
#define IDS_TRAFFIC_GBYTES              1076
#define IDC_EMAIL                       1077
#define IDC_VKONTAKTE                   1078
#define IDC_EMAILBUTTON                 1079
#define IDC_ICQ                         1080
#define IDC_ICQBUTTON                   1081
#define IDC_REGTIME                     1082
#define IDC_LASTJOIN                    1083
#define IDC_USERABOUT                   1084
#define IDC_THUMBNAIL                   1085
#define IDC_PHONE                       1086
#define IDC_EYES                        1087
#define IDC_HAIR                        1088
#define IDC_HEIGHT                      1089
#define IDC_MEETINGS                    1090
#define IDC_KNOWSFROM                   1091
#define IDC_LOCATION                    1092
#define IDC_ADD                         1093
#define IDC_REMOVE                      1094
#define IDC_CLEAR                       1095
#define IDC_MENU                        1096
#define IDC_ALARM                       1097
#define IDC_USERINFO                    1098
#define IDC_SORTBYSEX                   1099
#define IDC_SORTBYNICK                  1100
#define IDC_SEND                        1101
#define IDC_SORT                        1102
#define IDC_MARKASREAD                  1103
#define IDC_READTOPIC                   1104
#define IDC_PRECONFIG                   1105
#define IDC_NOPROXY                     1106
#define IDC_USEPROXY                    1107
#define IDC_PROXYNAME                   1108
#define IDC_PROXYPORT                   1109
#define IDC_PROXYAUTH                   1110
#define IDC_USERNAME                    1111
#define IDC_PASSWORD                    1112
#define IDC_HTMLCTRL                    1113
#define IDC_TEXT                        1115
#define IDS_AUTH_CREDENTIALS            1115
#define IDC_LINKLIST                    1117
#define IDC_AUTH                        32775
#define IDC_OPENPHOTO                   32776
#define IDC_LOGIN                       32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        298
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
